server:
  port: 9082
  error:
    include:
      message: true

logging:
  level:
    root: INFO

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: geo-service
  datasource:
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 10000
      max-lifetime: 1000
      auto-commit: true
    username: postgres
    password: secret
    url: 'jdbc:postgresql://localhost:5432/geo-service'
